title: Kenneth Teo
email: kenneth.teo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.kennethteo.com" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  kennethteo

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-coffeescript

github: [metadata]

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/